### PR TITLE
window: Replace GdkPixbuf with GdkTexture

### PR DESCRIPTION
**Pull request by A6GibKm**

### CODE REVIEW

**Comment by CleoMenezesJr** [comment]
Sorry, but what would be the difference in using texture instead of pixbuf?

**Comment by A6GibKm** [comment]
GdkPixbuf has been more or less unmaintained for a decade, texture is maintained. Also textures go more efficiently into the gpu when possible.

**Comment by CleoMenezesJr** [comment]
Since this PR I noticed something: The quality of the icons has dropped a lot. Previously, it was possible to set the original height and width of the image. With `Gdk.Texture.new_from_bytes` this is not possible.
https://github.com/CleoMenezesJr/Aurea/commit/54c655d19e50e01c75499ee2be69e633f76e520f#diff-dfe307d085487696ce56ef28d555c748f4e7b20a88aa0b6864e755e54e3dd2b3L187-L188

**Comment by A6GibKm** [comment]
Yes, this can happen because we upscale the icon. I would display them as 128x128 as that iss the original size, the alternative is to load them with librsvg directly. Let me thing a bit on this.

**Comment by CleoMenezesJr** [comment]
Nice. Come back to `GdkPixbuf.Pixbuf.new_from_data` is an option too.

**Comment by A6GibKm** [comment]
It is, but I think using librsvg or creating a custom paintable that upscales gracefully is a better option. Could you please tell me which app is the one with the blurry icon?

Of course if you need to do a release reverting that one part might be Ok.

**Comment by CleoMenezesJr** [comment]
> Could you please tell me which app is the one with the blurry icon?
All the apps I tested had low quality, but Emblem was the most notable.

> Of course if you need to do a release reverting that one part is Ok.
Thanks. I intend to release it as soon as the icon is ready. Until then, if there isn't some PR, I'll revert to GdkPixbuf.

**Pull request merged**
